resolver: nightly-2020-12-14

compiler: ghc-8.10.2

packages:
- .

extra-deps:
- git: git://github.com/hasktorch/hasktorch.git
  commit: 5b95ef51c73990241d3815eae1721306ef7204f7
  subdirs:
    - libtorch-ffi-helper
    - libtorch-ffi
    - hasktorch
- stm-2.5.0.0@sha256:c238075f9f0711cd6a78eab6001b3e218cdaa745d6377bf83cc21e58ceec2ea1,2100

nix:
  shell-file: nix/stack-shell.nix

allow-newer: true
